# Generated by Django 6.1 on 2026-09-06 15:21

import django.db.models.expressions
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransActoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porpuse', models.CharField(choices=[('wallet_charge', 'Charge Wallet'), ('appointment', 'Appointment')])),
                ('amount', models.FloatField()),
                ('authority', models.CharField()),
                ('card_number', models.CharField(blank=True, null=True)),
                ('creted_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
