# Generated by Django 6.1 on 2026-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv2',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='card',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='month',
            field=models.CharField(max_length=2),
        ),
    ]
