# Generated by Django 4.2.30 on 2026-09-03 20:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The payment amount recorded at the time of booking', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Consultation fee for this time slot (Tomans or Rials)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
