# Generated by Django 6.1 on 2026-09-05 14:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
