# Generated by Django 6.1 on 2026-09-05 14:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
