# Generated by Django 6.1 on 2026-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(related_name='specialities', to='doctors.speciality'),
        ),
    ]
