# Generated by Django 6.1 on 2026-09-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_speciality_doctor_doctor_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialities',
        ),
    ]
